### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by poonai** [GDGVIT/autodock#4]
add readme file.

**Comment by luvhalvorson** [comment]
Hi, I'm not familiar with docker and Go lang, would you like to tell me how to set this up? 
I just tried `docker build` . and then `docker run -it 31a207254dd6` and it's saying 
> http server started on [::]:41789 

</br>Am I on the right place? Thank you.

**Comment by poonai** [comment]
@luvhalvorson Thanks for showing your interest 
for building:
```
docker build -t <your username>/autodock .
```
for running
```
docker run -p 80:80 -e PORT=80 <your username>/autodock
```

**Comment by marceloabk** [comment]
I tried something in #9
